### ISSUE TITLE
intended to leave off semi-colon?

### ISSUE THREAD

**Issue by devinburnette** [learn-co-curriculum/javascript-intro-to-variable-assignment-and-declaration#1]
I know that semi-colons are optional a lot, but should we be consistent?

// declare the variable
var word;

// assign a value to the variable
word = 'bird';

console.log(word); // 'bird'

// assign another value to the variable
word = 'dog';

**console.log(word) // 'dog'**

**Comment by pletcher** [comment]
Thanks for being a part of the Learn community!

Keep in mind that this space is for specific issues related to the content of this lesson.

If you're reporting on the content of this lesson, it'd be super helpful if you could include a stack trace of any errors that you're seeing.

If you'd like to report a bug about the Learn IDE, the Ask a Question form, opening a file, or the lights not working on Learn, please report a bug directly on https://learn.co. (You can find the bug report form by clicking on your avatar in the upper right, and then selecting "Report A Bug".)

We want to respond as quickly as possible and be as helpful as possible, so please be sure to include steps to reproduce the issue (as best you can remember) and any pertinent details about your environment. (Are you using the Learn IDE? Coding from the ISS?) We'll figure out what's up and get back to you ASAP.
