### ISSUE TITLE
Not seeing all errors

### ISSUE THREAD

**Issue by briannaedin** [learn-co-curriculum/javascript-intro-to-variable-assignment-and-declaration#12]
When I run the test it is not matching the screenshots. I am not seeing " 3 test failing" I am only seeing the third error "
 Error: Expected 'space' to equal 'Let\'s talk about space.'     " in the terminal. I am have run the test in the index-test.js and the index.js folders. Is there a different file I should be running them in?

**Comment by JessRudder** [comment]
We have not had other issues reported on this lab.  Let us know if you are still having trouble getting the proper test output.
