### ISSUE TITLE
Intro to functions lab 

### ISSUE THREAD

**Issue by Ptrebat** [learn-co-curriculum/javascript-intro-to-variable-assignment-and-declaration#16]
I am having a difficult time correcting the errors of this lab.   I understand that the exercises be challenging to help learn through experience, yet I find there was not enough previous information given to successfully complete this lab within a reasonable time.  

I have noticed that many recent users are experiencing difficulty with this lab as well.  I feel that the lab is too vague.  I would like more information on working with strings inside of functions as it pertains to the lab if that is possible.

**Comment by gj** [comment]
Hi @Redclaun !

Your feedback is valuable, and we're currently reworking a good chunk of the early JavaScript material.

To help you get through the current lab, check out the [Ask a Question](http://help.learn.co/ask-a-question/where-can-i-ask-a-question-about-a-lesson) (AAQ) feature, where the [Technical Coaches](http://help.learn.co/instructional-support/receiving-course-support/who-are-the-technical-coaches) (on [supported tracks](http://help.learn.co/instructional-support/receiving-course-support/does-my-program-or-course-have-technical-coach-support)) and fellow community members can help you figure it out. For some tips on how to take full advantage of AAQ, check out [this helpful article](http://help.learn.co/ask-a-question/how-to-optimize-time-in-ask-a-question) in the [Learn Help Center](http://help.learn.co/).

Thanks! 💙

**Comment by maxwellbenton** [comment]
Hi @Ptrebat,

Thank you for this feedback. We've recently updated this lesson and the labs before and after to be more approachable and to include additional examples and guidance, which should hopefully prevent future students from facing the same challenges.

We apologize for any frustration this lesson may have caused, but we appreciate you taking the time to reach out and provide this feedback.

Thank you!
