### ISSUE TITLE
Missing semicolon

### ISSUE THREAD

**Issue by olegchursin** [learn-co-curriculum/javascript-intro-to-variable-assignment-and-declaration#18]
**Section title: MULTI-LINE VARIABLE ASSIGNMENT**
**Sentence:** ...which can be converted to: `var a = 5, b = 2, c = 3, d = 'hello', e = 'goodbye'`
**Needed change:** Missing semicolon at the end of variable declaration.

**Comment by maxwellbenton** [comment]
Hi @olegchursin,

Thank you for providing this feedback. We've updated this lesson and added in the missing semicolon  which should resolve this issue.
