### ISSUE TITLE
Javascript Variable assignment and declaration

### ISSUE THREAD

**Issue by AidenFoxPearce** [learn-co-curriculum/javascript-intro-to-variable-assignment-and-declaration#19]
In this module it says to try typing some variable names into the console and that I should see the value printed but for me it is not showing anything when I pull up the console. Does anybody know any common reasons I am not getting anything?

**Comment by maxwellbenton** [comment]
Hi @AidenFoxPearce,

Sorry to hear you were having difficulty with this content. Unfortunately, I am unable to replicate the issue you experienced. However, this content has recently been updated, and I can confirm that the content is working as intended currently.

We apologize for any frustration this may have caused, but we appreciate you taking the time to reach out and provide feedback.
