### ISSUE TITLE
Directions a bit unclear

### ISSUE THREAD

**Issue by d-d-d-dalia** [learn-co-curriculum/javascript-intro-to-variable-assignment-and-declaration#20]
Instructs students to follow along in the console, but not clear as to what that means in this lesson. They can open dev tools and do it that way.

**Comment by maxwellbenton** [comment]
Hey @d-d-d-dalia,

Although this is a bit late, we've updated this lesson's content and updated the instructions around using the console to provide more clarity. This should hopefully prevent confusion in future students.

Thank you for reporting this and letting us know!
