### ISSUE TITLE
Directions for following along are vague and unclear

### ISSUE THREAD

**Issue by jmulloy** [learn-co-curriculum/javascript-intro-to-variable-assignment-and-declaration#21]
The directions to follow along on this page are a bit unclear. Especially considering we have access to the sandbox site and the developer tools. It would be a little more helpful to let us know where we need to access the console from. 

Just a thought!

**Comment by maxwellbenton** [comment]
Hi @jmulloy,

Thank you for providing this feedback. We've updated this lesson's content and added additional guidance on how to follow along (either using `node` in the terminal, or opening a console in the browser), which should resolve this issue.

We apologize for any frustration this may have caused, but we appreciate you taking the time to let us know about your experience.

Thank you!
