### ISSUE TITLE
Sandbox

### ISSUE THREAD

**Issue by finerflower** [learn-co-curriculum/javascript-intro-to-variable-assignment-and-declaration#22]
Im typing commands in the sandbox but Im not seeing any changes when I type window.word.

Am I using the sandbox correctly?

**Comment by maxwellbenton** [comment]
Hi @finerflower, 

Thank you for providing this feedback and sorry to hear you were having difficulty with this lesson. We've updated this lesson's content and added additional guidance on how to follow along (either using node in the terminal or opening a console in the browser), which should resolve this issue.

We apologize for any frustration this may have caused, but we appreciate you taking the time to let us know about your experience.

Thank you!
