### ISSUE TITLE
BreakPoint pushes console content below visible area inside Learn ide when minimizing window.

### ISSUE THREAD

**Issue by AlexanderNelson** [learn-co-curriculum/javascript-intro-to-variable-assignment-and-declaration#5]
With the console docked in the editor and content filling the visible area of the console, If the window width is adjusted below approx 2/3 screen-width the console content is pushed below the bottom of the window and cannot be seen even when scrolled all the way down. It must be forced to redraw the content which can be seen by either adjusting font-size(ctrl-shift-"-" or "+") or undocking and redocking the console from the Editor. It will also return to normal if returning to fullscreen. This may prevent users from being able to view the llesson in the browser and work in the IDE on the same shared screen without forcing the redraw mentioned above. In the attached image, the page is scrolled to its lower limit and there is two lines that can not be viewed at the bottom of the console.
![learnline](https://cloud.githubusercontent.com/assets/16615147/17896430/9d6a4926-691e-11e6-87c7-78aae672febf.PNG)

**Comment by AnnJohn** [comment]
hi @AlexanderNelson this is a known product issue but thanks  for raising it. i'm going to close this for now here. 

in the future if you notice buggy things with features or the product, could you file a bug report? if you click on your profile pic in Learn, you'll see a menu with an option there to Report a Bug. Thanks!

**Comment by AlexanderNelson** [comment]
Ahhh, yes. I didn't see that "raise an issue" and "report a bug" were
different.

**Comment by AnnJohn** [comment]
no problem! thanks for helping us improve the product and curriculum!
