### ISSUE TITLE
No semicolon

### ISSUE THREAD

**Issue by WebMaster0738** [learn-co-curriculum/javascript-intro-to-variable-assignment-and-declaration#8]
Not sure if this is of much contribution but the third console image under the multi line variable part of JavaScript Variable Assignment and Declaration free course doesn't end the line with a semicolon. Not sure if it is or isnt intentional. Just figured I'd bring it up...

**Comment by AnnJohn** [comment]
hi @WebMaster0738 thanks for raising the issue and nothing is too small! could you please post a screenshot? not sure specifically where in the lesson this is. thanks.
